/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MarketPlaceMessage {
  'text' : string,
  'productId' : bigint,
  'sender' : string,
  'timestamp' : Time,
}
export interface Product {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'isSold' : boolean,
  'seller' : Principal,
  'imageUrl' : string,
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'autos' : null } |
  { 'home' : null } |
  { 'sports' : null } |
  { 'fashion' : null } |
  { 'electronics' : null } |
  { 'hobbies' : null };
export interface SupportMessage {
  'text' : string,
  'sender' : string,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, bigint, ProductCategory, string, string],
    bigint
  >,
  'getAllProductsSorted' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMarketPlaceMessagesByProduct' : ActorMethod<
    [bigint],
    Array<MarketPlaceMessage>
  >,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getSupportMessages' : ActorMethod<[], Array<SupportMessage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markProductAsSold' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMarketPlaceMessage' : ActorMethod<[bigint, string, string], undefined>,
  'sendSupportMessage' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];